// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC26s1RIf1oQ1GY_UQ8PeNm6A8hybsPJXE',
    appId: '1:1047194107990:web:9a22d38775d04cf3597bf7',
    messagingSenderId: '1047194107990',
    projectId: 'my-todo-bbe5d',
    authDomain: 'my-todo-bbe5d.firebaseapp.com',
    databaseURL: 'https://my-todo-bbe5d-default-rtdb.firebaseio.com',
    storageBucket: 'my-todo-bbe5d.appspot.com',
    measurementId: 'G-6DYBBVWCQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfjduQs19_mK6LQkfPrZ7wcObFFFykqvI',
    appId: '1:1047194107990:android:2cf41cdc4db20dec597bf7',
    messagingSenderId: '1047194107990',
    projectId: 'my-todo-bbe5d',
    databaseURL: 'https://my-todo-bbe5d-default-rtdb.firebaseio.com',
    storageBucket: 'my-todo-bbe5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgvrN4eHxoH6hvxeJPdEhrE_HPcOvvCiA',
    appId: '1:1047194107990:ios:46d86f89d6457fe7597bf7',
    messagingSenderId: '1047194107990',
    projectId: 'my-todo-bbe5d',
    databaseURL: 'https://my-todo-bbe5d-default-rtdb.firebaseio.com',
    storageBucket: 'my-todo-bbe5d.appspot.com',
    iosBundleId: 'com.example.myTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgvrN4eHxoH6hvxeJPdEhrE_HPcOvvCiA',
    appId: '1:1047194107990:ios:13d1714374d878ab597bf7',
    messagingSenderId: '1047194107990',
    projectId: 'my-todo-bbe5d',
    databaseURL: 'https://my-todo-bbe5d-default-rtdb.firebaseio.com',
    storageBucket: 'my-todo-bbe5d.appspot.com',
    iosBundleId: 'com.example.myTodo.RunnerTests',
  );
}
